import { errorHandler } from "../utils/errorHandler";
export const predictionsOverview = async (req, res) => {
    try {
        res.status(200).json({
            success: true,
            data: {}
        });
    }
    catch (error) {
        errorHandler(error, req, res);
    }
};
export const getAllPredictions = async (req, res) => {
    try {
        res.status(200).json({
            success: true,
            data: {}
        });
    }
    catch (error) {
        errorHandler(error, req, res);
    }
};
export const getMatchPredictions = async (req, res) => {
    try {
        res.status(200).json({
            success: true,
            data: {}
        });
    }
    catch (error) {
        errorHandler(error, req, res);
    }
};
export const getAllActivePredictions = async (req, res) => {
    try {
        res.status(200).json({
            success: true,
            data: {}
        });
    }
    catch (error) {
        errorHandler(error, req, res);
    }
};
export const getAllSuccessfulPredictions = async (req, res) => {
    try {
        res.status(200).json({
            success: true,
            data: {}
        });
    }
    catch (error) {
        errorHandler(error, req, res);
    }
};
export const getAllFailedPredictions = async (req, res) => {
    try {
        res.status(200).json({
            success: true,
            data: {}
        });
    }
    catch (error) {
        errorHandler(error, req, res);
    }
};
export const betBuilder = async (req, res) => {
    try {
        res.status(200).json({
            success: true,
            data: {}
        });
    }
    catch (error) {
        errorHandler(error, req, res);
    }
};
